credentials:
  usernames:
    admin:
      email: "admin@tuempresa.com"
      name: "Administrador"
      password: "$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6L6s5866jH6u6u6u"
cookie:
  expiry_days: 30
  key: "llave_secreta_cerebro"
  name: "cerebro_cookie"
