import streamlit as st

def gestionar_login():
    # Inicializamos el estado si no existe
    if "autenticado" not in st.session_state:
        st.session_state["autenticado"] = False

    if not st.session_state["autenticado"]:
        st.markdown("<h2 style='color: #00FBFF;'>ðŸ”’ ACCESO AL CEREBRO</h2>", unsafe_allow_html=True)
        
        with st.form("login_form"):
            user = st.text_input("Usuario")
            password = st.text_input("ContraseÃ±a", type="password")
            submit = st.form_submit_button("INGRESAR")

            if submit:
                # Comprobamos contra los Secretos de la App
                # Puedes usar 'admin' y '123' temporalmente aquÃ­ para probar
                if user == "admin" and password == "123":
                    st.session_state["autenticado"] = True
                    st.rerun()
                else:
                    st.error("Credenciales no autorizadas")
        return False
    
    return True
